sudo: false

cache: pip

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - poppler-utils # document index
      - antiword # document index
      - python-ldap # auth_ldap
      - wkhtmltopdf # report_webkit

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - rm -rf ${HOME}/${ODOO_REPO#*/}-${VERSION}; ln -s ${TRAVIS_BUILD_DIR} ${HOME}/${ODOO_REPO#*/}-${VERSION}
  - cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .

script:
  - export INCLUDE=$(getaddons.py -m ${HOME}/build/${ODOO_REPO}/openerp/addons ${HOME}/build/${ODOO_REPO}/addons)
    # tests of document_ftp and delivery fail. The following two are excluded because they depend on delivery
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery
  - export INSTALL_OPTIONS="--without-demo=account"
  - SERVER_PATH=${HOME}/${ODOO_REPO#*/}-${VERSION}
  - export TRAVIS_BUILD_DIR=${SERVER_PATH}/openerp/addons
  - travis_run_tests

after_success:
  - travis_after_tests_success
