language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:911.0"
#  - "sh -e /etc/init.d/xvfb start"

env:
  - VERSION="11.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"


install:
  - ln -s ${HOME}/build/${ODOO_REPO} ${HOME}/${ODOO_REPO#*/}-${VERSION}
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - pip install -Ur ${HOME}/maintainer-quality-tools/requirements.txt
  - pip install -Ur ${HOME}/build/${ODOO_REPO}/requirements.txt
  - pip install -q QUnitSuite flake8 coveralls pylint
  - npm install -g less less-plugin-clean-css
  - (cd ${HOME}/maintainer-quality-tools/travis/ && wget -qO- -t 1 --timeout=240 https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz | tar -xJ --strip-components=2 wkhtmltox/bin/wkhtmltopdf)
  - sed -i "s/'phantomjs'/'disable_phantomjs'/g" ${TRAVIS_BUILD_DIR}/odoo/tests/common.py
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - export INCLUDE=$(getaddons.py -m ${HOME}/build/${ODOO_REPO}/odoo/addons ${HOME}/build/${ODOO_REPO}/addons)
  - export EXCLUDE=hw_scanner,hw_escpos,theme_bootswatch
  - cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .

script:
  - SERVER_PATH=${HOME}/${ODOO_REPO#*/}-${VERSION}
  - export TRAVIS_BUILD_DIR=${SERVER_PATH}/odoo/addons
  - travis_run_tests

after_success:
  - travis_after_tests_success
